# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dB22vS5MTSpGs8Ay5zkrokpPNyq6DwEm
"""

pip install pycaret[full]

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from statsmodels.tsa.arima.model import ARIMA

df = pd.read_csv('/week03_updated_cleaned_data.csv')
df['time'] = pd.to_datetime(df['time'])
df.set_index('time', inplace=True)

# Filter for the "Bursty Job"
data = df[df['job_type'] == 'Bursty Job']['cpu_cores']

# FEATURE ENGINEERING
ml_data = pd.DataFrame(data)
ml_data['Lag_1'] = ml_data['cpu_cores'].shift(1)
ml_data['Lag_2'] = ml_data['cpu_cores'].shift(2)
ml_data['Lag_3'] = ml_data['cpu_cores'].shift(3)
ml_data['Rolling_Mean_12'] = ml_data['cpu_cores'].rolling(window=12).mean()
ml_data.dropna(inplace=True)

# 3. SPLIT DATA (80/20 split)
train_size = int(len(ml_data) * 0.8)
train, test = ml_data.iloc[:train_size], ml_data.iloc[train_size:]

X_train, y_train = train.drop('cpu_cores', axis=1), train['cpu_cores']
X_test, y_test = test.drop('cpu_cores', axis=1), test['cpu_cores']

# LINEAR REGRESSION (Simple Baseline)
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)

# RANDOM FOREST
rf = RandomForestRegressor(n_estimators=100, random_state=123)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)

# ARIMA (Statistical Baseline)
arima_train = data.iloc[:train_size]
arima_model = ARIMA(arima_train, order=(5,1,0))
arima_fit = arima_model.fit()
arima_pred = arima_fit.forecast(steps=len(y_test))

# 4. LEADERBOARD
results = {
    'Model': ['Linear Regression', 'Random Forest', 'ARIMA'],
    'MAE': [
        mean_absolute_error(y_test, lr_pred),
        mean_absolute_error(y_test, rf_pred),
        mean_absolute_error(y_test, arima_pred)
    ],
    'RMSE': [
        np.sqrt(mean_squared_error(y_test, lr_pred)),
        np.sqrt(mean_squared_error(y_test, rf_pred)),
        np.sqrt(mean_squared_error(y_test, arima_pred))
    ]
}

leaderboard = pd.DataFrame(results).sort_values(by='MAE')
print("\n--- MODEL LEADERBOARD ---")
print(leaderboard)

# Save for report
leaderboard.to_csv('model_leaderboard.csv', index=False)

# 5. VISUALIZE THE WINNER
best_model_name = leaderboard.iloc[0]['Model']
best_preds = rf_pred if best_model_name == 'Random Forest' else (lr_pred if best_model_name == 'Linear Regression' else arima_pred)

plt.figure(figsize=(12, 6))
# Plot just the last 200 points to make it readable
plt.plot(y_test.index[:200], y_test.values[:200], label='Actual Demand', color='black', alpha=0.7)
plt.plot(y_test.index[:200], best_preds[:200], label=f'Best Model ({best_model_name})', color='red', linestyle='--')
plt.title(f"Forecast Comparison: {best_model_name} Wins! (MAE: {leaderboard.iloc[0]['MAE']:.2f})")
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('Best_Model_Forecast.png')
plt.show()